# Generated by Django 4.2.10 on 2024-04-23 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("logisticians", "0002_logisticianuser"),
    ]

    operations = [
        migrations.RenameField(
            model_name="logisticianuser",
            old_name="logicianInfos",
            new_name="logisticianInfos",
        ),
    ]
