# Generated by Django 4.2.10 on 2024-04-23 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("logisticians", "0003_rename_logicianinfos_logisticianuser_logisticianinfos"),
    ]

    operations = [
        migrations.RenameField(
            model_name="logisticianuser",
            old_name="logisticianInfos",
            new_name="logistician_infos",
        ),
    ]
