# Generated by Django 4.2.10 on 2024-04-09 20:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("packages", "0002_alter_package_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="package",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pending Dropoff", "Pending Dropoff"),
                    ("In Shipping", "In Shipping"),
                ],
                max_length=100,
            ),
        ),
    ]
